namespace DeviceTools.HumanInterfaceDevices
{
    public enum HidUsagePage : ushort
    {
        Undefined = 0x00,
        GenericDesktop = 0x01,
        Simulation = 0x02,
        Vr = 0x03,
        Sport = 0x04,
        Game = 0x05,
        GenericDevice = 0x06,
        Keyboard = 0x07,
        Led = 0x08,
        Button = 0x09,
        Ordinal = 0x0A,
        Telephony = 0x0B,
        Consumer = 0x0C,
        Digitizer = 0x0D,
		Haptics = 0x0E,
		PhysicalInterfaceDevice = 0x0F,
        Unicode = 0x10,
		EyeAndHeadTrackers = 0x12,
        AuxiliaryDisplay = 0x14,
        Sensor = 0x20,
		MedicalInstrument = 0x40,
		BrailleDisplay = 0x41,
		LightingAndIllumination = 0x59,
		UsbMonitor = 0x80,
		UsbEnumeratedValues = 0x81,
		VesaVirtualControls = 0x82,
		// MonitorReserved = 0x83,
		PowerDevice = 0x84,
		BatterySystem = 0x85,
		// PowerDeviceReserved1 = 0x86,
		// PowerDeviceReserved2 = 0x87,
		BarcodeScanner = 0x8C,
        WeighingDevice = 0x8D,
        MagneticStripeReader = 0x8E,
		// PointOfSaleReserved = 0x8F,
        CameraControl = 0x90,
        Arcade = 0x91,
        GamingDevice = 0x92,
		FidoAlliance = 0xF1D0,
		MicrosoftBluetoothHandsfree = 0xFFF3,
    }
}
