using DeviceTools;

namespace Exo;

public static class DeviceInterfaceClassExtensions
{
	public static Guid ToGuid(this DeviceInterfaceClass deviceInterfaceClass)
		=> deviceInterfaceClass switch
		{
			DeviceInterfaceClass.Parallel => DeviceInterfaceClassGuids.Parallel,
			DeviceInterfaceClass.ParallelClass => DeviceInterfaceClassGuids.ParallelClass,
			DeviceInterfaceClass.UsbHub => DeviceInterfaceClassGuids.UsbHub,
			DeviceInterfaceClass.UsbBillboard => DeviceInterfaceClassGuids.UsbBillboard,
			DeviceInterfaceClass.UsbDevice => DeviceInterfaceClassGuids.UsbDevice,
			DeviceInterfaceClass.UsbHostController => DeviceInterfaceClassGuids.UsbHostController,
			DeviceInterfaceClass.Keyboard => DeviceInterfaceClassGuids.Keyboard,
			DeviceInterfaceClass.Mouse => DeviceInterfaceClassGuids.Mouse,
			DeviceInterfaceClass.Hid => DeviceInterfaceClassGuids.Hid,
			DeviceInterfaceClass.DisplayOutputInterfaceStandard => DeviceInterfaceClassGuids.DisplayOutputInterfaceStandard,
			DeviceInterfaceClass.DisplayAdapter => DeviceInterfaceClassGuids.DisplayAdapter,
			DeviceInterfaceClass.Monitor => DeviceInterfaceClassGuids.Monitor,
			DeviceInterfaceClass.DisplayDeviceArrival => DeviceInterfaceClassGuids.DisplayDeviceArrival,
			DeviceInterfaceClass.VideoOutputArrival => DeviceInterfaceClassGuids.VideoOutputArrival,
			DeviceInterfaceClass.Disk => DeviceInterfaceClassGuids.Disk,
			DeviceInterfaceClass.CdRom => DeviceInterfaceClassGuids.CdRom,
			DeviceInterfaceClass.Partition => DeviceInterfaceClassGuids.Partition,
			DeviceInterfaceClass.Tape => DeviceInterfaceClassGuids.Tape,
			DeviceInterfaceClass.WriteOnceDisk => DeviceInterfaceClassGuids.WriteOnceDisk,
			DeviceInterfaceClass.Volume => DeviceInterfaceClassGuids.Volume,
			DeviceInterfaceClass.MediumChanger => DeviceInterfaceClassGuids.MediumChanger,
			DeviceInterfaceClass.Floppy => DeviceInterfaceClassGuids.Floppy,
			DeviceInterfaceClass.CdChanger => DeviceInterfaceClassGuids.CdChanger,
			DeviceInterfaceClass.StoragePort => DeviceInterfaceClassGuids.StoragePort,
			DeviceInterfaceClass.VmLun => DeviceInterfaceClassGuids.VmLun,
			DeviceInterfaceClass.Ses => DeviceInterfaceClassGuids.Ses,
			DeviceInterfaceClass.ServiceVolume => DeviceInterfaceClassGuids.ServiceVolume,
			DeviceInterfaceClass.HiddenVolume => DeviceInterfaceClassGuids.HiddenVolume,
			DeviceInterfaceClass.UnifiedAccessRpmb => DeviceInterfaceClassGuids.UnifiedAccessRpmb,
			DeviceInterfaceClass.ComPort => DeviceInterfaceClassGuids.ComPort,
			DeviceInterfaceClass.SerialAndParallelPort => DeviceInterfaceClassGuids.SerialAndParallelPort,
			DeviceInterfaceClass.Modem => DeviceInterfaceClassGuids.Modem,
			DeviceInterfaceClass.Net => DeviceInterfaceClassGuids.Net,
			DeviceInterfaceClass.I2C => DeviceInterfaceClassGuids.I2C,
			DeviceInterfaceClass.Opm => DeviceInterfaceClassGuids.Opm,
			DeviceInterfaceClass.Opm2Jtp => DeviceInterfaceClassGuids.Opm2Jtp,
			DeviceInterfaceClass.Opm2 => DeviceInterfaceClassGuids.Opm2,
			DeviceInterfaceClass.Opm3 => DeviceInterfaceClassGuids.Opm3,
			DeviceInterfaceClass.Brightness => DeviceInterfaceClassGuids.Brightness,
			DeviceInterfaceClass.Brightness2 => DeviceInterfaceClassGuids.Brightness2,
			DeviceInterfaceClass.MiracastDisplay => DeviceInterfaceClassGuids.MiracastDisplay,
			DeviceInterfaceClass.Image => DeviceInterfaceClassGuids.Image,
			DeviceInterfaceClass.SideShow => DeviceInterfaceClassGuids.SideShow,
			DeviceInterfaceClass.Wpd => DeviceInterfaceClassGuids.Wpd,
			DeviceInterfaceClass.WpdPrivate => DeviceInterfaceClassGuids.WpdPrivate,
			DeviceInterfaceClass.WpdService => DeviceInterfaceClassGuids.WpdService,
			DeviceInterfaceClass.Battery => DeviceInterfaceClassGuids.Battery,
			DeviceInterfaceClass.ApplicationLaunchButton => DeviceInterfaceClassGuids.ApplicationLaunchButton,
			DeviceInterfaceClass.SystemButton => DeviceInterfaceClassGuids.SystemButton,
			DeviceInterfaceClass.Lid => DeviceInterfaceClassGuids.Lid,
			DeviceInterfaceClass.ThermalZone => DeviceInterfaceClassGuids.ThermalZone,
			DeviceInterfaceClass.Fan => DeviceInterfaceClassGuids.Fan,
			DeviceInterfaceClass.Processor => DeviceInterfaceClassGuids.Processor,
			DeviceInterfaceClass.Memory => DeviceInterfaceClassGuids.Memory,
			DeviceInterfaceClass.AcpiTime => DeviceInterfaceClassGuids.AcpiTime,
			DeviceInterfaceClass.MessageIndicator => DeviceInterfaceClassGuids.MessageIndicator,
			DeviceInterfaceClass.ThermalCooling => DeviceInterfaceClassGuids.ThermalCooling,
			DeviceInterfaceClass.VirtualAudioVideoControl => DeviceInterfaceClassGuids.VirtualAudioVideoControl,
			DeviceInterfaceClass.AudioVideoControl => DeviceInterfaceClassGuids.AudioVideoControl,
			DeviceInterfaceClass.BluetoothPort => DeviceInterfaceClassGuids.BluetoothPort,
			DeviceInterfaceClass.BluetoothRfcommService => DeviceInterfaceClassGuids.BluetoothRfcommService,
			DeviceInterfaceClass.Bluetooth => DeviceInterfaceClassGuids.Bluetooth,
			DeviceInterfaceClass.BluetoothLe => DeviceInterfaceClassGuids.BluetoothLe,
			DeviceInterfaceClass.BluetoothGattService => DeviceInterfaceClassGuids.BluetoothGattService,
			_ => throw new ArgumentOutOfRangeException()
		};
}
