namespace AnyLayout.RawInput
{
    public enum HidSimulationUsage : ushort
    {
        Undefined = 0x00,

        FlightSimulationDevice = 0x01,
        AutomobileSimulationDevice = 0x02,
        TankSimulationDevice = 0x03,
        SpaceshipSimulationDevice = 0x04,
        SubmarineSimulationDevice = 0x05,
        SailingSimulationDevice = 0x06,
        MotorcycleSimulationDevice = 0x07,
        SportsSimulationDevice = 0x08,
        AirplaneSimulationDevice = 0x09,
        HelicopterSimulationDevice = 0x0A,
        MagicCarpetSimulationDevice = 0x0B,
        BicylceSimulationDevice = 0x0C,

        FlightControlStick = 0x20,
        FlightStick = 0x21,
        CyclicControl = 0x22,
        CyclicTrim = 0x23,
        FlightYoke = 0x24,
        TrackControl = 0x25,

        Aileron = 0xB0,
        AileronTrim = 0xB1,
        AntiTorqueControl = 0xB2,
        AutopilotEnable = 0xB3,
        ChaffRelease = 0xB4,
        CollectiveControl = 0xB5,
        DiveBrake = 0xB6,
        ElectronicCountermeasures = 0xB7,
        Elevator = 0xB8,
        ElevatorTrim = 0xB9,
        Rudder = 0xBA,
        Throttle = 0xBB,
        FlightCommunications = 0xBC,
        FlareRelease = 0xBD,
        LandingGear = 0xBE,
        ToeBrake = 0xBF,
        Trigger = 0xC0,
        WeaponsArm = 0xC1,
        WeaponsSelect = 0xC2,
        WingFlaps = 0xC3,
        Accelerator = 0xC4,
        Brake = 0xC5,
        Clutch = 0xC6,
        Shifter = 0xC7,
        Steering = 0xC8,
        TurretDirection = 0xC9,
        BarrelElevation = 0xCA,
        DivePlante = 0xCB,
        Ballast = 0xCC,
        BicycleCrank = 0xCD,
        HandleBars = 0xCE,
        FrontBrake = 0xCF,
        RearBrake = 0xD0,
    }

    public enum HidSportUsage : ushort
    {
        Undefined = 0x00,
        BaseballBat = 0x00,
        GolfClub = 0x01,
        RowingMachine = 0x02,
        Treadmill = 0x03,

        Oar = 0x30,
        Slope = 0x31,
        Rate = 0x32,
        StickSpeed = 0x33,
        StickFaceAngle = 0x34,
        StickHeelToe = 0x35,
        StickFollowThrough = 0x36,
        StickTempo = 0x37,
        StickType = 0x38,
        StickHeight = 0x39,

        Putter = 0x50,
        Iron1 = 0x51,
        Iron2 = 0x52,
        Iron3 = 0x53,
        Iron4 = 0x54,
        Iron5 = 0x55,
        Iron6 = 0x56,
        Iron7 = 0x57,
        Iron8 = 0x58,
        Iron9 = 0x59,
        Iron10 = 0x5A,
        Iron11 = 0x5B,
        SandWedge = 0x5C,
        LoftWedge = 0x5D,
        PowerWedge = 0x5E,
        Wood1 = 0x5F,
        Wood3 = 0x60,
        Wood5 = 0x61,
        Wood7 = 0x62,
        Wood9 = 0x63,
    }

    public enum HidGenericDeviceControlUsage : ushort
    {
        Undefined = 0x00,

        BatteryStrength = 0x20,
        WirelessChannel = 0x21,
        WirelessId = 0x22,
        DiscoverWirelessControl = 0x23,
        SecurityCodeCharacterEntered = 0x24,
        SecurityCodeCharacterErased = 0x25,
        SecurityCodeCleared = 0x26,
    }
}
