namespace DeviceTools.HumanInterfaceDevices.Usages
{
	public enum HidAuxiliaryDisplayUsage : ushort
	{
		Undefined = 0x00,
		AlphanumericDisplay = 0x01,
		AuxiliaryDisplay = 0x02,

		DisplayAttributesReport = 0x20,
		AsciiCharacterSet = 0x21,
		DataReadBack = 0x22,
		FontReadBack = 0x23,
		DisplayControlReport = 0x24,
		ClearDisplay = 0x25,
		DisplayEnable = 0x26,
		ScreenSaverDelay = 0x27,
		ScreenSaverEnable = 0x28,
		VerticalScroll = 0x29,
		HorizontalScroll = 0x2A,
		CharacterReport = 0x2B,
		DisplayData = 0x2C,
		DisplayStatus = 0x2D,
		StatNotReady = 0x2E,
		StatReady = 0x2F,
		ErrorNotALoadableCharacter = 0x30,
		ErrorFontDataCannotBeRead = 0x31,
		CursorPositionReport = 0x32,
		Row = 0x33,
		Column = 0x34,
		Rows = 0x35,
		Columns = 0x36,
		CursorPixelPositioning = 0x37,
		CursorMode = 0x38,
		CursorEnable = 0x39,
		CursorBlink = 0x3A,
		FontReport = 0x3B,
		FontDataBufferedBytes = 0x3C,
		CharacterWidth = 0x3D,
		CharacterHeight = 0x3E,
		CharacterSpacingHorizontal = 0x3F,
		CharacterSpacingVertical = 0x40,
		UnicodeCharacterSet = 0x41,
		Font7Segment = 0x42,
		DirectMap7Segment = 0x43,
		Font14Segment = 0x44,
		DirectMap14Segment = 0x45,
		DisplayBrightness = 0x46,
		DisplayContrast = 0x47,
		CharacterAttribute = 0x48,
		AttributeReadback = 0x49,
		AttributeData = 0x4A,
		CharAttrEnhance = 0x4B,
		CharAttrUnderline = 0x4C,
		CharAttrBlink = 0x4D,

		BitmapSizeX = 0x80,
		BitmapSizeY = 0x81,
		MaxBlitSize = 0x82,
		BitDepthFormat = 0x83,
		DisplayOrientation = 0x84,
		PaletteReport = 0x85,
		PaletteDataSize = 0x86,
		PaletteDataOffset = 0x87,
		PaletteDataBufferedBytes = 0x88,

		BlitReport = 0x8A,
		BlitRectangleX1 = 0x8B,
		BlitRectangleY1 = 0x8C,
		BlitRectangleX2 = 0x8D,
		BlitRectangleY2 = 0x8E,
		BlitData = 0x8F,
		SoftButton = 0x90,
		SoftButtonId = 0x91,
		SoftButtonSide = 0x92,
		SoftButtonOffset1 = 0x93,
		SoftButtonOffset2 = 0x94,
		SoftButtonReport = 0x95,

		SoftKeys = 0xC2,

		DisplayDataExtensions = 0xCC,

		CharacterMapping = 0xCF,

		UnicodeEquivalent = 0xDD,

		CharacterPageMapping = 0xDF,

		RequestReport = 0xFF,
	}
}
