namespace DeviceTools.HumanInterfaceDevices.Usages
{
    public enum HidGenericDesktopUsage : ushort
    {
        Undefined = 0x00,

        Pointer = 0x01,
        Mouse = 0x02,
        Joystick = 0x04,
        Gamepad = 0x05,
        Keyboard = 0x06,
        Keypad = 0x07,
        MultiAxisController = 0x08,
        TabletPcSystemControls = 0x09,
        WaterCoolingDevice = 0x0A,
		ComputerChassisDevice = 0x0B,
		WirelessRadioControl = 0x0C,
		PortableDeviceControl = 0x0D,
        SystemMultiAxisController = 0x0E,
        SpatialController = 0x0F,
        AssistiveControl = 0x10,
		DeviceDock = 0x11,
		DockabelDevice = 0x12,

		X = 0x30,
        Y = 0x31,
        Z = 0x32,
        Rx = 0x33,
        Ry = 0x34,
        Rz = 0x35,
        Slider = 0x36,
        Dial = 0x37,
        Wheel = 0x38,
        HatSwitch = 0x39,

        CountedBuffer = 0x3A,
        ByteCount = 0x3B,

        MotionWakeup = 0x3C,
        Start = 0x3D,
        Select = 0x3E,

        Vx = 0x40,
        Vy = 0x41,
        Vz = 0x42,
        VbrX = 0x43,
        VbrY = 0x44,
        VbrZ = 0x45,
        Vno = 0x46,

        FeatureNotification = 0x47,

        ResolutionMultiplier = 0x48,

		Qx = 0x49,
		Qy = 0x4A,
		Qz = 0x4B,
		Qw = 0x4C,

		SystemControl = 0x80,
        SystemPower = 0x81,
        SystemSleep = 0x82,
        SystemWake = 0x83,
        SystemContextMenu = 0x84,
        SystemMainMenu = 0x85,
        SystemAppMenu = 0x86,
        SystemHelpMenu = 0x87,
        SystemMenuExit = 0x88,
        SystemMenuSelect = 0x89,
        SystemMenuRight = 0x8A,
        SystemMenuLeft = 0x8B,
        SystemMenuUp = 0x8C,
        SystemMenuDown = 0x8D,
        SystemColdRestart = 0x8E,
        SystemWarmRestart = 0x8F,

        DirectionPadUp = 0x90,
        DirectionPadDown = 0x91,
        DirectionPadRight = 0x92,
        DirectionPadLeft = 0x93,

        IndexTrigger = 0x94,
        PalmTrigger = 0x95,
        Thumbstick = 0x96,

		SystemFunctionShift = 0x97,
		SystemFunctionShiftLock = 0x98,
		SystemFunctionShiftLockIndicator = 0x99,
		SystemDismissNotification = 0x9A,
		SystemDoNotDisturb = 0x9B,

		SystemDock = 0xA0,
        SystemUndock = 0xA1,
        SystemSetup = 0xA2,
        SystemBreak = 0xA3,
        SystemDebuggerBreak = 0xA4,
        ApplicationBreak = 0xA5,
        ApplicationDebuggerBreak = 0xA6,
        SystemSpeakerMute = 0xA7,
        SystemHibernate = 0xA8,

        SystemDisplayInvert = 0xB0,
        SystemDisplayInternal = 0xB1,
        SystemDisplayExternal = 0xB2,
        SystemDisplayBoth = 0xB3,
        SystemDisplayDual = 0xB4,
        SystemDisplayToggleInternalExternal = 0xB5,
        SystemDisplaySwapPrimarySecondary = 0xB6,
        SystemDisplayLcdAutoscale = 0xB7,

		SensorZone = 0xC0,
		Rpm = 0xC1,
		CoolantLevel = 0xC3,
		CoolantCriticalLevel = 0xC3,
		CoolantPump = 0xC4,
		ChassisEnclosure = 0xC5,

		WirelessRadioButton = 0xC6,
		WirelessRadioLed = 0xC7,
		WirelessRadioSliderSwitch = 0xC8,

		SystemDisplayRotationLockButton = 0xC9,
        SystemDisplayRotationLockSliderSwitch = 0xCA,
        ControlEnable = 0xCB,

		DockableDeviceUniqueId = 0xD0,
		DockableDeviceVendorId = 0xD1,
		DockableDevicePrimaryUsagePage = 0xD2,
		DockableDevicePrimaryUsageId = 0xD3,
		DockableDeviceDockingState = 0xD4,
		DockableDeviceDisplayOcclusion = 0xD5,
		DockableDeviceObjectType = 0xD6,

    }
}
