namespace DeviceTools.HumanInterfaceDevices.Usages;

public enum HidBatterySystemUsage : ushort
{
	Undefined = 0x00,
	SmartBatteryBatteryMode = 0x01,
	SmartBatteryBatteryStatus = 0x02,
	SmartBatteryAlarmWarning = 0x03,
	SmartBatteryChargerMode = 0x04,
	SmartBatteryChargerStatus = 0x05,
	SmartBatteryChargerSpecInfo = 0x06,
	SmartBatterySelectorState = 0x07,
	SmartBatterySelectorPresets = 0x08,
	SmartBatterySelectorInfo = 0x09,

	OptionalMfgFunction1 = 0x10,
	OptionalMfgFunction2 = 0x11,
	OptionalMfgFunction3 = 0x12,
	OptionalMfgFunction4 = 0x13,
	OptionalMfgFunction5 = 0x14,
	ConnectionToSmBus = 0x15,
	OutputConnection = 0x16,
	ChargerConnection = 0x17,
	BatteryInsertion = 0x18,
	UseNext = 0x19,
	OkToUse = 0x1A,
	BatterySupported = 0x1B,
	SelectorRevision = 0x1C,
	ChargingIndicator = 0x1D,

	ManufacturerAccess = 0x28,
	RemainingCapacityLimit = 0x29,
	RemainingTimeLimit = 0x2A,
	AtRate = 0x2B,
	CapacityMode = 0x2C,
	BroadcastToCharger = 0x2D,
	PrimaryBattery = 0x2E,
	ChargeController = 0x2F,

	TerminateCharge = 0x40,
	TerminateDischarge = 0x41,
	BelowRemainingCapacityLimit = 0x42,
	RemainingTimeLimitExpired = 0x43,
	Charging = 0x44,
	Discharging = 0x45,
	FullyCharged = 0x46,
	FullyDischarged = 0x47,
	ConditioningFlag = 0x48,
	AtRateOk = 0x49,
	SmbErrorCode = 0x4A,
	NeedReplacement = 0x4B,

	AtRateTimeToFull = 0x60,
	AtRateTimeToEmpty = 0x61,
	AverageCurrent = 0x62,
	MaxError = 0x63,
	RelativeStateOfCharge = 0x64,
	AbsoluteStateOfCharge = 0x65,
	RemainingCapacity = 0x66,
	FullChargeCapacity = 0x67,
	RunTimeToEmpty = 0x68,
	AverageTimeToEmpty = 0x69,
	AverageTimeToFull = 0x6A,
	CycleCount = 0x6B,

	BattPackModelLevel = 0x80,
	InternalChargeController = 0x81,
	PrimaryBatterySupport = 0x82,
	DesignCapacity = 0x83,
	SpecificationInfo = 0x84,
	ManufacturerDate = 0x85,
	SerialNumber = 0x86,
	ManufacturerNameIndex = 0x87,
	DeviceNameIndex = 0x88,
	DeviceChemistryIndex = 0x89,
	ManufacturerData = 0x8A,
	Rechargeable = 0x8B,
	WarningCapacityLimit = 0x8C,
	CapacityGranularity1 = 0x8D,
	CapacityGranularity2 = 0x8E,
	OemInformationIndex = 0x8F,

	InhibitCharge = 0xC0,
	EnablePolling = 0xC1,
	ResetToZero = 0xC2,
	AcPresent = 0xD0,
	BatteryPresent = 0xD1,
	PowerFail = 0xD2,
	AlarmInhibited = 0xD3,
	ThermistorUnderRange = 0xD4,
	ThermistorHot = 0xD5,
	ThermistorCold = 0xD6,
	ThermistorOverRange = 0xD7,
	VoltageOutOfRange = 0xD8,
	CurrentOutOfRange = 0xD9,
	CurrentNotRegulated = 0xDA,
	VoltageNotRegulated = 0xDB,
	MasterMode = 0xDC,

	ChargerSelectorSupport = 0xF0,
	ChargerSpec = 0xF1,
	Level2 = 0xF2,
	Level3 = 0xF3,
}
