name: Build and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    steps:
    - name: Identify artifact version
      run: Add-Content -Path $env:GITHUB_ENV -Value "ARTIFACT_VERSION=$(Get-Date -Format yyyy-MM-dd)-$env:GITHUB_SHA"

    - name: Prepare MSI artifact name
      run: Add-Content -Path $env:GITHUB_ENV -Value "MSI_ARTIFACT_NAME=Exo Installer $env:ARTIFACT_VERSION"

    - name: Prepare binaries artifact name
      run: Add-Content -Path $env:GITHUB_ENV -Value "BINARIES_ARTIFACT_NAME=Exo Binaries $env:ARTIFACT_VERSION"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild Exo.slnx /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Build the WiX project, which depends on the main projects
    - name: Build the installer
      run: msbuild src\Exo\Exo.InstallerPackage\Exo.InstallerPackage.wixproj /t:Build /p:Configuration=$env:Configuration /p:Platform=x64 /p:OutputName="$env:MSI_ARTIFACT_NAME"
      env:
        Configuration: ${{ matrix.configuration }}

    # Publish the artifact containing the MSI installer
    - name: Upload MSI Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.MSI_ARTIFACT_NAME }}
        path: src\Exo\Exo.InstallerPackage\bin\x64\Release\en-US\${{ env.MSI_ARTIFACT_NAME }}.msi

    # Publish the artifact containing the binaries
    - name: Upload Binaries Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.BINARIES_ARTIFACT_NAME }}
        path: src\Exo\Exo.InstallerPackage\obj\x64\Release\publish\
        compression-level: 9

